# Nome da aplicacao
spring.application.name=biblioteca

# Configuracoes de Conexao com o Supabase (PostgreSQL)
spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.nmzgxcxnjclnrhzrslmw
spring.datasource.password=Menolli#1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracoes do Hibernate/JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true